---
engines:
  rubocop:
    enabled: true
    channel: rubocop-0-54
    config:
      file: .rubocop.yml
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
    - app/**
    - lib/**
    - "**.rb"
exclude_paths:
  - spec/**/*
  - vendor/**/*
  - docs/**/*
