---
require:
  - 'rubocop-performance'
  - 'rubocop-rspec'

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - '.bundle/**/*'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
