language: ruby
sudo: false
notifications:
  email: false
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: "96b0a00d9fbb060ff9c0bcd3b9d7b331bad32250dbb9b9258b9d0553534209c2"
env:
  - SECRET_KEY_BASE=3726902eb363750966ae9879eff39e77f0c7508b7e2128365fcc9c65c02d113c04dbf571cc83dbf49967b0ddb1e57cdcd88f0195652662586ce92d0601811f04
rvm:
  - 2.2.3
before_install:
  - gem install bundler
  - gem install rspec
  - gem install rubocop
script:
  - RAILS_ENV=test bundle exec rake db:migrate:reset
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test bundle exec rake spec
  - rubocop --fail-level=W
