language: ruby
sudo: false
notifications:
  email: false
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: "2890b837cc0aa8583b1ab866b022a8947e94cbe07621a323a3c8afd2714df6f6"
env:
  - SECRET_KEY_BASE=3726902eb363750966ae9879eff39e77f0c7508b7e2128365fcc9c65c02d113c04dbf571cc83dbf49967b0ddb1e57cdcd88f0195652662586ce92d0601811f04
rvm:
  - 2.3.1
before_install:
  - gem install bundler
  - gem install rspec
  - gem install rubocop
script:
  - RAILS_ENV=test bundle exec rake db:migrate:reset
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test bundle exec rake spec
  - rubocop --fail-level=W
