---
app-name: 'aniwatch'
author-id: 'supercaracal'
author-name: 'PocaPocaUnty'
tv-channel:
  ch1:   'NHK総合'
  ch2:   'Eテレ'
  ch4:   '日本テレビ'
  ch5:   'テレビ朝日'
  ch6:   'TBSテレビ'
  ch7:   'テレビ東京'
  ch8:   'フジテレビ'
  ch9:   'TOKYO MX'
  ch3:   'テレ玉'
  ch103: 'BSプレミアム'
  ch161: 'BS-TBS'
  ch181: 'BSフジ'
  ch211: 'BS11'
day-of-week:
  - { id: 'mon', name: '月' }
  - { id: 'tue', name: '火' }
  - { id: 'wed', name: '水' }
  - { id: 'thu', name: '木' }
  - { id: 'fri', name: '金' }
  - { id: 'sat', name: '土' }
  - { id: 'sun', name: '日' }
slot-of-day:
  - { id: 'midnight', name: '深夜', color: 'danger',  from: 0,  to: 5  }
  - { id: 'daytime',  name: '日中', color: 'info',    from: 5,  to: 16 }
  - { id: 'sunset',   name: '夕方', color: 'success', from: 16, to: 19 }
  - { id: 'night',    name: '夜',   color: 'warning', from: 19, to: 24 }
lineups:
  - { title: '進撃の巨人', start_time: '00:10', channel: ch1, day_of_week: mon }
  - { title: '7SEEDS', start_time: '22:30', channel: ch9, day_of_week: mon }
  - { title: 'たとえばラストダンジョン前の村の少年が序盤の街で暮らすような物語', start_time: '23:00', channel: ch9, day_of_week: mon }
  - { title: 'ウマ娘', start_time: '00:00', channel: ch9, day_of_week: tue }
  - { title: '裏世界ピクニック', start_time: '00:30', channel: ch9, day_of_week: tue }
  - { title: 'ブラッククローバー', start_time: '18:30', channel: ch7, day_of_week: tue }
  - { title: '転生したらスライムだった件', start_time: '23:00', channel: ch9, day_of_week: tue }
  - { title: '七つの大罪', start_time: '18:00', channel: ch7, day_of_week: wed }
  - { title: '魔術士オーフェンはぐれ旅', start_time: '22:00', channel: ch9, day_of_week: wed }
  - { title: 'Re:ゼロから始める異世界生活', start_time: '23:30', channel: ch9, day_of_week: wed }
  - { title: 'オルタンシア・サーガ', start_time: '00:30', channel: ch9, day_of_week: thu }
  - { title: 'BEASTARS', start_time: '01:30', channel: ch8, day_of_week: thu }
  - { title: 'ゆるキャン', start_time: '23:30', channel: ch9, day_of_week: thu }
  - { title: '天地創造デザイン部', start_time: '00:00', channel: ch9, day_of_week: fri }
  - { title: 'ひぐらしのなく頃に業', start_time: '00:30', channel: ch9, day_of_week: fri }
  - { title: '約束のネバーランド', start_time: '02:00', channel: ch8, day_of_week: fri }
  - { title: 'ポケットモンスター', start_time: '19:00', channel: ch7, day_of_week: fri }
  - { title: '弱キャラ友崎くん', start_time: '22:00', channel: ch9, day_of_week: fri }
  - { title: '蜘蛛ですが、なにか?', start_time: '22:30', channel: ch9, day_of_week: fri }
  - { title: 'バック・アロウ', start_time: '00:00', channel: ch9, day_of_week: sat }
  - { title: 'おとなの防具屋さん', start_time: '01:00', channel: ch9, day_of_week: sat }
  - { title: '呪術廻戦', start_time: '02:00', channel: ch6, day_of_week: sat }
  - { title: '俺だけ入れる隠しダンジョン', start_time: '03:00', channel: ch6, day_of_week: sat }
  - { title: 'ドラゴンクエスト ダイの大冒険', start_time: '09:30', channel: ch7, day_of_week: sat }
  - { title: '半妖の夜叉姫', start_time: '17:30', channel: ch4, day_of_week: sat }
  - { title: 'はたらく細胞!!', start_time: '23:30', channel: ch9, day_of_week: sat }
  - { title: 'はたらく細胞 BLACK', start_time: '00:00', channel: ch9, day_of_week: sun }
  - { title: 'Levius', start_time: '01:00', channel: ch9, day_of_week: sun }
  - { title: 'ワールドトリガー', start_time: '01:30', channel: ch5, day_of_week: sun }
  - { title: 'ワンピース', start_time: '09:30', channel: ch8, day_of_week: sun }
  - { title: 'BORUTO', start_time: '17:30', channel: ch7, day_of_week: sun }
  - { title: '怪物事変', start_time: '22:00', channel: ch9, day_of_week: sun }
  - { title: 'SuperGT', start_time: '23:30', channel: ch7, day_of_week: sun }
