# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a6895435c68d47b57a33a63655d0a12500b646634821fa229ce90b2410dc7c6d13cb3d44ca03dced92cf78fcfbcbc99c152a467c246b960120306a86d4f6029

test:
  secret_key_base: 3f2ed9056643fa4c55ab511c4fd14a105f243013e15d37082fc9abfedacda7bede038140ee6b0cbece70155052566cb4451385bc1f41c535d823e83bd68bc509

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
