---
# @see https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: CI
on:
  push:
    branches:
      - "*"
jobs:
  test:
    name: Test
    timeout-minutes: 5
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        go-ver: ["1.15"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-ver }}

      - name: Add $GOPATH/bin to $PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Get dependencies
        run: go get golang.org/x/lint/golint

      - name: Test
        run: make test

      - name: Lint
        run: make lint
