---
# @see https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Test
on:
  push:
    branches:
      - "*"
jobs:
  test:
    name: Test
    timeout-minutes: 5
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        go-ver: ["1.17"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-ver }}

      - name: Get dependencies
        run: go install golang.org/x/lint/golint@latest

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Bench
        run: make bench

      - name: Profiling (lineup)
        run: make prof
        env:
          PKG: lineup

      - name: Profiling (middleware)
        run: make prof
        env:
          PKG: middleware
