---
# @see https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    name: Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: Download modules
        run: go mod download
      - name: Run
        run: make lint
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: Download modules
        run: go mod download
      - name: Run
        run: make test
  benchmark:
    name: Benchmark
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: Download modules
        run: go mod download
      - name: Run
        run: make bench
  profiling:
    name: Profiling
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ["lineup", "middleware"]
        type: ["cpu", "block", "mem"]
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: Download modules
        run: go mod download
      - name: Run
        run: make prof
        env:
          PKG: ${{ matrix.package }}
          TYPE: ${{ matrix.type }}
